name: burn_cell

on: [pull_request]
jobs:
  burn_cell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get AMReX
        run: |
          mkdir external
          cd external
          git clone https://github.com/AMReX-Codes/amrex.git
          cd amrex
          git checkout development
          echo 'AMREX_HOME=$(GITHUB_WORKSPACE)/external/amrex' >> $GITHUB_ENV
          echo $AMREX_HOME
          if [[ -n "${AMREX_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++>=9.3.0

      - name: Compile, burn_cell (VODE, subch_approx)
        run: |
          cd unit_test/burn_cell
          make realclean
          make NETWORK_DIR=subch_approx -j 4

      - name: Run burn_cell (VODE, subch_approx)
        run: |
          cd unit_test/burn_cell
          ./main3d.gnu.ex inputs_subch_approx > test.out

      - name: Compare to stored output (VODE, subch_approx)
        run: |
          cd unit_test/burn_cell
          diff -I "^AMReX" -I "^reading in reaclib rates" test.out ci-benchmarks/subch_approx_unit_test.out

      - name: Compile, burn_cell (VODE, ECSN)
        run: |
          cd unit_test/burn_cell
          make realclean
          make NETWORK_DIR=ECSN -j 4

      - name: Run burn_cell (VODE, ECSN)
        run: |
          cd unit_test/burn_cell
          ./main3d.gnu.ex inputs_ecsn > test.out

      - name: Compare to stored output (ECSN)
        run: |
          cd unit_test/burn_cell
          diff -I "^AMReX" -I "^reading in reaclib rates" test.out ci-benchmarks/ecsn_unit_test.out

      - name: Compile, burn_cell (BackwardEuler, subch_approx)
        run: |
          cd unit_test/burn_cell
          make realclean
          make NETWORK_DIR=subch_approx INTEGRATOR_DIR=BackwardEuler -j 4

      - name: Run burn_cell (BackwardEuler, subch_approx)
        run: |
          cd unit_test/burn_cell
          ./main3d.gnu.ex inputs_subch_approx > test.out

      - name: Compare to stored output (BackwardEuler, subch_approx)
        run: |
          cd unit_test/burn_cell
          diff -I "^AMReX" -I "^reading in reaclib rates" test.out ci-benchmarks/subch_approx_BE_unit_test.out

      - name: Compile, burn_cell (QSS, aprox13)
        run: |
          cd unit_test/burn_cell
          make realclean
          make NETWORK_DIR=aprox13 INTEGRATOR_DIR=QSS -j 4

      - name: Run burn_cell (QSS, aprox13)
        run: |
          cd unit_test/burn_cell
          ./main3d.gnu.ex inputs_aprox13 > test.out

      - name: Compare to stored output (QSS, aprox13)
        run: |
          cd unit_test/burn_cell
          diff -I "^AMReX" -I "^reading in reaclib rates" test.out ci-benchmarks/aprox13_QSS_unit_test.out

      - name: Compile, burn_cell (NSE, aprox19)
        run: |
          cd unit_test/burn_cell
          make realclean
          make NETWORK_DIR=aprox19 USE_NSE=TRUE INTEGRATOR_DIR=VODE -j 4

      - name: Run burn_cell (NSE, aprox19)
        run: |
          cd unit_test/burn_cell
          ./main3d.gnu.ex inputs_aprox19.nse > test.out

      - name: Compare to stored output (NSE, aprox19)
        run: |
          cd unit_test/burn_cell
          diff -I "^AMReX" -I "^reading in reaclib rates" test.out ci-benchmarks/aprox19_nse_unit_test.out


