name: burn_cell_primordial_chem

on: [pull_request]

jobs:
  burn_cell_primordial_chem:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get AMReX
        run: |
          mkdir external
          cd external
          git clone https://github.com/AMReX-Codes/amrex.git
          cd amrex
          git checkout development
          echo 'AMREX_HOME=$(GITHUB_WORKSPACE)/external/amrex' >> $GITHUB_ENV
          echo $AMREX_HOME
          if [[ -n "${AMREX_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++>=9.3.0

      - name: Compile and run
        run: |
          cd unit_test/burn_cell_primordial_chem
          make -j 2
          ./main1d.gnu.DEBUG.ex inputs_primordial_chem > test.out

      - name: Compare to stored output
        run: |
          set -e
          cd unit_test/burn_cell_primordial_chem
          line_numbers=(456 458 460 463 465 471 476)
          threshold=0.01
          error_found=false
          for line_number in "${line_numbers[@]}"; do

            value1=$(awk 'NR=='"$line_number"' {match($0, /[+-]?[0-9]+([.][0-9]+)?[eE]?[+-]?[0-9]+/); if (RSTART) print substr($0, RSTART, RLENGTH)}' test.out)
            value2=$(awk 'NR=='"$line_number"' {match($0, /[+-]?[0-9]+([.][0-9]+)?[eE]?[+-]?[0-9]+/); if (RSTART) print substr($0, RSTART, RLENGTH)}' reference_solution.out)

            ratio=$(awk -v val1="$value1" -v val2="$value2" 'BEGIN { printf "%.2f", val1 / val2 }')

            if (( $(echo "$ratio/$value1 > $threshold" | bc -l) )); then
              echo "Line number: $line_number"
              echo "Value in test.out: $value1"
              echo "Value in reference_solution.out: $value2"
              echo "Difference between test and reference value is more than allowed threshold of $threshold"
              echo
              error_found=true
            fi
          done
          if [[ $error_found == true ]]; then
            exit 1
          fi

