name: nse_net

on: [pull_request]
jobs:
  nse_net:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get AMReX
        run: |
          mkdir external
          cd external
          git clone https://github.com/AMReX-Codes/amrex.git
          cd amrex
          git checkout development
          echo 'AMREX_HOME=$(GITHUB_WORKSPACE)/external/amrex' >> $GITHUB_ENV
          echo $AMREX_HOME
          if [[ -n "${AMREX_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++>=9.3.0

      - name: Compile, test_nse_net (NSE_NET, ase)
        run: |
          cd unit_test/test_nse_net
          make realclean
          make -j 4

      - name: Run test_nse_net (NSE_NET, ase)
        run: |
          cd unit_test/test_nse_net
          ./main3d.gnu.ex inputs_ase amrex.fpe_trap_{invalid,zero,overflow}=1 > test.out

      - name: Print backtrace
        if: ${{ failure() && hashFiles('unit_test/test_nse_net/Backtrace.0') != '' }}
        run: cat unit_test/test_nse_net/Backtrace.0

      - name: Compare to stored output (NSE_NET, ase)
        run: |
          cd unit_test/test_nse_net
          diff -I "^Initializing AMReX" -I "^AMReX" -I "^reading in reaclib rates" test.out ci-benchmarks/ase_nse_net_unit_test.out

      - name: Compile, test_nse_net/make_table (NSE_NET, ase, make_table)
        run: |
          cd unit_test/test_nse_net/make_table
          make realclean
          make -j 4

      - name: Run, test_nse_net/make_table (NSE_NET, ase, make_table)
        run: |
          cd unit_test/test_nse_net/make_table
          ./main3d.gnu.ex amrex.fpe_trap_{invalid,zero,overflow}=1 > test.out

      - name: Print backtrace
        if: ${{ failure() && hashFiles('unit_test/test_nse_net/make_table/Backtrace.0') != '' }}
        run: cat unit_test/test_nse_net/make_table/Backtrace.0

      - name: Compare to stored output (NSE_NET, ase, make_table)
        run: |
          cd unit_test/test_nse_net/make_table
          diff -I "^Initializing AMReX" -I "^AMReX" -I "^reading in reaclib rates" test.out ci-benchmarks/ase_nse_net_make_table_unit_test.out
